version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.0
  env_file:
    - ../.env
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    DOCKER_HOST: unix:///var/run/docker.sock
    _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-docker google-cloud-bigquery"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
    - ../shared_keys:/opt/airflow/shared_keys
  networks:
    - airflow_network
  depends_on:
    postgres:
      condition: service_healthy

networks:
  airflow_network:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Son --lastname Nguyen --role Admin --email admin@example.com"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: unless-stopped